import { test, expect } from '@playwright/test';

const stamp = Date.now();
test('register, create work, invite by username and accept in-app', async ({ page, browser }) => {
  await page.goto('/register');
  await page.getByLabel('Full name').fill('Demo Tester');
  await page.getByLabel('Username').fill(`tester.${stamp}`);
  await page.getByLabel('Email').fill(`tester.${stamp}@example.test`);
  await page.getByLabel('Password').fill('Testing@123');
  await page.getByRole('button',{name:/create account/i}).click();
  await expect(page).toHaveURL(/onboarding/);
  await page.getByLabel('Organisation name').fill(`Test Org ${stamp}`);
  await page.getByRole('button',{name:/create organisation/i}).click();
  const origin = new URL(page.url()).origin;
  const inviteeContext = await browser.newContext();
  const inviteePage = await inviteeContext.newPage();
  const inviteeUsername = `invitee.${stamp}`;
  await inviteePage.goto(`${origin}/register`);
  await inviteePage.getByLabel('Full name').fill('Invited Tester');
  await inviteePage.getByLabel('Username').fill(inviteeUsername);
  await inviteePage.getByLabel('Email').fill(`invitee.${stamp}@example.test`);
  await inviteePage.getByLabel('Password').fill('Testing@123');
  await inviteePage.getByRole('button',{name:/create account/i}).click();
  await expect(inviteePage).toHaveURL(/onboarding/);
  await page.getByRole('link',{name:'Projects'}).click();
  await page.getByRole('button',{name:/new project/i}).click();
  await page.locator('input[name="name"]').fill('E2E Project');
  await page.getByRole('button',{name:/save project/i}).click();
  await page.getByRole('link',{name:'E2E Project'}).click();
  await page.getByRole('button',{name:/new task/i}).click();
  await page.locator('input[name="title"]').fill('Verify onboarding flow');
  await page.getByRole('button',{name:/create task/i}).click();
  await page.getByText('Verify onboarding flow').click();
  await page.getByRole('dialog').locator('select').first().selectOption({ label: 'In Progress' });
  await page.getByPlaceholder(/write a comment/i).fill('E2E comment');
  await page.getByRole('button',{name:'Send'}).click();
  await expect(page.getByText('E2E comment')).toBeVisible();
  await page.getByLabel('Close modal').click();
  await page.getByRole('link',{name:'Team'}).click();
  await page.getByRole('button',{name:/invite member/i}).click();
  await page.getByRole('dialog').locator('input[name="username"]').fill(inviteeUsername);
  await page.getByRole('button',{name:/send invitation/i}).click();
  await inviteePage.reload();
  await expect(inviteePage.getByText(/pending team invitations/i)).toBeVisible();
  await inviteePage.getByRole('button',{name:'Accept'}).click();
  await expect(inviteePage).toHaveURL(/dashboard/);
  await page.getByRole('link',{name:'Chat'}).click();
  await page.getByRole('button',{name:/invited tester/i}).click();
  await page.getByLabel('Message').fill('Welcome to the project 🎉');
  await page.getByRole('button',{name:'Send message'}).click();
  await inviteePage.getByRole('link',{name:'Chat'}).click();
  await inviteePage.getByRole('button',{name:/demo tester/i}).click();
  await expect(inviteePage.getByText('Welcome to the project 🎉')).toBeVisible();
  await inviteeContext.close();
});
