import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowRight, CheckCircle2, Eye, EyeOff, FolderKanban } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext.jsx';
import { authApi } from '../api';
import { Button, FieldError } from '../components/ui.jsx';

const loginSchema = z.object({ email: z.string().email('Enter a valid email'), password: z.string().min(1, 'Password is required') });
const registerSchema = z.object({ fullName: z.string().min(2, 'Enter your full name'), username: z.string().regex(/^[a-z0-9._-]{3,30}$/i, 'Use 3–30 letters, numbers, dots or underscores'), email: z.string().email(), password: z.string().min(8).regex(/[A-Z]/, 'Add an uppercase letter').regex(/[a-z]/, 'Add a lowercase letter').regex(/[0-9]/, 'Add a number') });
const Shell = ({ children, title, subtitle }) => <div className="min-h-screen bg-canvas p-4 dark:bg-[#1c0d25]"><div className="mx-auto grid min-h-[calc(100vh-2rem)] max-w-6xl overflow-hidden rounded-3xl bg-card shadow-2xl dark:bg-plum-900 lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-gradient-to-br from-plum-950 to-plum-900 p-12 text-white lg:flex lg:flex-col"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-coral/20 blur-3xl"/><div className="relative flex items-center gap-3 text-2xl font-black"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-coral">T</span>TaskFlow</div><div className="relative my-auto"><p className="mb-4 text-sm font-bold uppercase tracking-[.25em] text-coral">Work flows better</p><h2 className="max-w-md text-5xl font-black leading-tight">Plan, collaborate, and deliver together.</h2><div className="mt-10 space-y-4 text-white/75">{['Visual Kanban planning','Real-time team collaboration','Clear workload and progress insights'].map((v)=><p className="flex items-center gap-3" key={v}><CheckCircle2 className="text-coral" size={20}/>{v}</p>)}</div></div><p className="relative text-sm text-white/45">Professional multi-tenant project management.</p></section><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 text-xl font-black lg:hidden"><span className="grid h-9 w-9 place-items-center rounded-xl bg-coral text-white">T</span>TaskFlow</Link><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-muted">{subtitle}</p><div className="mt-8">{children}</div></div></section></div></div>;

const PasswordInput = ({ register, error }) => { const [visible,setVisible]=useState(false); const id=`field-${register.name}`; return <div><label className="label" htmlFor={id}>Password</label><div className="relative"><input id={id} className="input pr-11" type={visible?'text':'password'} {...register}/><button type="button" aria-label="Toggle password visibility" onClick={()=>setVisible(!visible)} className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2 text-muted">{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><FieldError message={error}/></div>; };
export function LoginPage() { const { login }=useAuth(); const navigate=useNavigate(); const { register,handleSubmit,formState:{errors,isSubmitting} }=useForm({resolver:zodResolver(loginSchema),defaultValues:{email:'owner@taskflow.demo',password:'Demo@123'}}); const submit=async(v)=>{try{await login(v);toast.success('Welcome back');navigate('/dashboard');}catch(e){toast.error(e.response?.data?.message||'Login failed');}}; return <Shell title="Welcome back" subtitle="Log in to continue to your workspace."><form className="space-y-5" onSubmit={handleSubmit(submit)}><div><label className="label" htmlFor="login-email">Email</label><input id="login-email" className="input" type="email" autoComplete="email" {...register('email')}/><FieldError message={errors.email?.message}/></div><PasswordInput register={register('password')} error={errors.password?.message}/><div className="flex justify-end"><Link className="text-sm font-semibold text-coral" to="/forgot-password">Forgot password?</Link></div><Button className="w-full" loading={isSubmitting}>Log in <ArrowRight size={18}/></Button><p className="text-center text-sm text-muted">New to TaskFlow? <Link className="font-bold text-coral" to="/register">Create an account</Link></p></form></Shell>; }
export function RegisterPage() { const { register:signUp }=useAuth(); const navigate=useNavigate(); const { register,handleSubmit,formState:{errors,isSubmitting} }=useForm({resolver:zodResolver(registerSchema)}); const submit=async(v)=>{try{await signUp(v);toast.success('Account created');navigate('/onboarding');}catch(e){toast.error(e.response?.data?.message||'Registration failed');}}; return <Shell title="Create your account" subtitle="Start organising your team in minutes."><form className="space-y-4" onSubmit={handleSubmit(submit)}><div><label className="label" htmlFor="register-name">Full name</label><input id="register-name" className="input" {...register('fullName')}/><FieldError message={errors.fullName?.message}/></div><div><label className="label" htmlFor="register-username">Username</label><input id="register-username" className="input" placeholder="alex.morgan" {...register('username')}/><FieldError message={errors.username?.message}/></div><div><label className="label" htmlFor="register-email">Email</label><input id="register-email" className="input" type="email" {...register('email')}/><FieldError message={errors.email?.message}/></div><PasswordInput register={register('password')} error={errors.password?.message}/><Button className="w-full" loading={isSubmitting}>Create account <ArrowRight size={18}/></Button><p className="text-center text-sm text-muted">Already have an account? <Link className="font-bold text-coral" to="/login">Log in</Link></p></form></Shell>; }
export function ForgotPasswordPage() { const {register,handleSubmit,formState:{isSubmitting}}=useForm(); const [sent,setSent]=useState(false); const submit=async(v)=>{try{await authApi.forgot(v);setSent(true);}catch(e){toast.error(e.response?.data?.message||'Request failed');}}; return <Shell title="Reset your password" subtitle="We’ll send instructions if the account exists.">{sent?<div className="rounded-2xl bg-success/10 p-6 text-center"><CheckCircle2 className="mx-auto text-success" size={36}/><p className="mt-3 font-bold">Check your email</p><p className="mt-1 text-sm text-muted">Reset instructions are valid for 30 minutes.</p><Link className="mt-5 inline-block font-bold text-coral" to="/login">Back to login</Link></div>:<form className="space-y-5" onSubmit={handleSubmit(submit)}><div><label className="label">Email</label><input className="input" type="email" required {...register('email')}/></div><Button className="w-full" loading={isSubmitting}>Send reset link</Button></form>}</Shell>; }
export function ResetPasswordPage() { const [params]=useSearchParams(); const navigate=useNavigate(); const {register,handleSubmit,formState:{isSubmitting}}=useForm(); const submit=async(v)=>{try{await authApi.reset({token:params.get('token'),password:v.password});toast.success('Password reset');navigate('/login');}catch(e){toast.error(e.response?.data?.message||'Reset failed');}}; return <Shell title="Choose a new password" subtitle="Use at least 8 characters with uppercase, lowercase and a number."><form className="space-y-5" onSubmit={handleSubmit(submit)}><PasswordInput register={register('password')} /><Button className="w-full" loading={isSubmitting}>Update password</Button></form></Shell>; }
