import { useEffect, useRef } from 'react';
import { X, AlertCircle, Inbox } from 'lucide-react';

export const Button = ({ variant = 'primary', loading, children, className = '', ...props }) => <button className={`${variant === 'primary' ? 'btn-primary' : variant === 'danger' ? 'btn bg-danger text-white hover:bg-red-600' : 'btn-secondary'} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />}{children}</button>;
export const Card = ({ className = '', children, ...props }) => <div className={`card ${className}`} {...props}>{children}</div>;
export const Avatar = ({ user, size = 'md' }) => { const classes = { sm: 'h-7 w-7 text-xs', md: 'h-9 w-9 text-sm', lg: 'h-12 w-12 text-base' }; return user?.avatar ? <img className={`${classes[size]} rounded-full object-cover ring-2 ring-white/70`} src={user.avatar} alt={user.fullName || 'User'} /> : <span className={`${classes[size]} inline-flex items-center justify-center rounded-full bg-coral/15 font-bold text-coral ring-1 ring-coral/20`}>{(user?.fullName || '?').split(' ').map((v) => v[0]).slice(0,2).join('').toUpperCase()}</span>; };
export const Badge = ({ children, color = 'bg-plum-900/10 text-plum-900 dark:bg-white/10 dark:text-white' }) => <span className={`badge ${color}`}>{children}</span>;
export const Skeleton = ({ className = 'h-20' }) => <div aria-label="Loading" className={`animate-pulse rounded-2xl bg-line/60 dark:bg-white/10 ${className}`} />;
export const EmptyState = ({ title = 'Nothing here yet', text = 'Create your first item to get started.', action }) => <div className="flex min-h-52 flex-col items-center justify-center rounded-2xl border border-dashed border-line p-8 text-center dark:border-white/10"><span className="mb-3 rounded-2xl bg-coral/10 p-3 text-coral"><Inbox /></span><h3 className="font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted">{text}</p>{action && <div className="mt-4">{action}</div>}</div>;
export const ErrorState = ({ message = 'Something went wrong', retry }) => <div role="alert" className="flex items-center justify-between gap-4 rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger"><span className="flex items-center gap-2"><AlertCircle size={18} />{message}</span>{retry && <button className="font-bold underline" onClick={retry}>Retry</button>}</div>;
export const Modal = ({ open, onClose, title, children, size = 'max-w-xl' }) => {
  const ref = useRef(); useEffect(() => { if (!open) return; const listener = (e) => e.key === 'Escape' && onClose(); document.addEventListener('keydown', listener); const previous = document.activeElement; setTimeout(() => ref.current?.focus(), 0); return () => { document.removeEventListener('keydown', listener); previous?.focus(); }; }, [open, onClose]);
  if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-plum-950/55 p-4" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="modal-title" className={`max-h-[90vh] w-full overflow-y-auto rounded-2xl bg-card shadow-2xl outline-none dark:bg-plum-900 ${size}`}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-line bg-card/95 px-5 py-4 backdrop-blur dark:border-white/10 dark:bg-plum-900/95"><h2 id="modal-title" className="text-lg font-bold">{title}</h2><button aria-label="Close modal" className="rounded-lg p-2 hover:bg-canvas dark:hover:bg-white/10" onClick={onClose}><X size={20}/></button></div><div className="p-5">{children}</div></div></div>;
};
export const FieldError = ({ message }) => message ? <p className="mt-1 text-xs text-danger">{message}</p> : null;
export const PageHeader = ({ title, description, actions }) => <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-black tracking-tight text-ink dark:text-white">{title}</h1>{description && <p className="mt-1 text-sm text-muted">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
export const Progress = ({ value = 0 }) => <div className="h-2 overflow-hidden rounded-full bg-line/70 dark:bg-white/10"><div className="h-full rounded-full bg-coral transition-all" style={{ width: `${Math.min(Math.max(value,0),100)}%` }}/></div>;
